//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReturning
    {
        public int Id { get; set; }
        public System.DateTime Real_Return_Date { get; set; }
    
        public virtual Penalty Penalty { get; set; }
        public virtual BookGiving BookGiving { get; set; }
        public virtual Librarian Librarian { get; set; }
    }
}
