//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BookGiving
    {
        //[Key,ForeignKey("BookReturning")]
        public int Id { get; set; }
        public System.DateTime Give_Date { get; set; }
        public System.DateTime Expected_Return_Date { get; set; }
    
        public virtual BookReturning BookReturning { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
