//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int Id { get; set; }
        public string Info { get; set; }
        public decimal Sum { get; set; }
    
        public virtual BookReturning BookReturning { get; set; }
    }
}
