//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Дата рождения")]
        public System.DateTime Birthday { get; set; }
        [Phone]
        [Display(Name = "Номер телефона")]
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        [Required()]
        public virtual Address Address { get; set; }
    }
}
