//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.BookGiving = new HashSet<BookGiving>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BBK { get; set; }
        public string UDK { get; set; }
        public string Author { get; set; }
        public bool Available { get; set; }
        public string ISBN { get; set; }
        public int Page_Count { get; set; }
        public string Release_Number { get; set; }
        public int Year { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookGiving> BookGiving { get; set; }
    }
}
